### ISSUE TITLE
Error when running a webpack compile

### ISSUE THREAD

**Issue by vjpr** [papandreou/node-mountfs#3]
```
Uncaught TypeError: path.indexOf is not a function
      at findVirtualPathAndMountedFsAndMountPath (node_modules/mountfs/lib/MountFs.js:63:22)
      at Object.that.(anonymous function) [as write] (node_modules/mountfs/lib/MountFs.js:87:40)
      at writeAll (fs.js:1098:6)
      at fs.js:1139:7
      at node_modules/mountfs/lib/MountFs.js:153:32
      at FSReqWrap.oncomplete (node_modules/mock-fs/node/fs-4.0.0.js:72:15)
```

What could be causing it? Using with `mock-fs` module.

**Comment by gustavnikolaj** [comment]
What are you trying to do, could you give a little more context, and maybe a small snippet that can reproduce the error?

**Comment by gustavnikolaj** [comment]
Feel free to reopen this issue if it's still a problem.
